#!/bin/sh
wget -O /home/nhoss003/socrata2/King-County-Sheriff-s-Office+4h35-4mtu.csv https://moto.data.socrata.com/api/views/4h35-4mtu/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Santa-Clara-County-Sheriff-s-Office+wrmr-tdyp.csv https://moto.data.socrata.com/api/views/wrmr-tdyp/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Santa-Rosa-County-Sheriff-s-Office+5c4j-6cka.csv https://moto.data.socrata.com/api/views/5c4j-6cka/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Harris-County-Sheriff-s-Office+p6kq-vsa3.csv https://moto.data.socrata.com/api/views/p6kq-vsa3/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Flagler-County-Sheriff-s-Office+9tv5-g2uz.csv https://moto.data.socrata.com/api/views/9tv5-g2uz/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Long-Beach-Police-Department+du6n-4fyc.csv https://moto.data.socrata.com/api/views/du6n-4fyc/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Lee-County-Sheriff-s-Office+c2jd-w27w.csv https://moto.data.socrata.com/api/views/c2jd-w27w/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Vallejo-Police-Department+6h36-wpzf.csv https://moto.data.socrata.com/api/views/6h36-wpzf/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Campbell-Police-Department+shz2-ig3z.csv https://moto.data.socrata.com/api/views/shz2-ig3z/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Fulton-County-Police-Department+w67x-hhdz.csv https://moto.data.socrata.com/api/views/w67x-hhdz/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Jefferson-County-Sheriff-s-Office+kk9h-r9zr.csv https://moto.data.socrata.com/api/views/kk9h-r9zr/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Clovis-Police-Department+38iu-bd67.csv https://moto.data.socrata.com/api/views/38iu-bd67/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Redwood-City-Police+9wfx-9qes.csv https://moto.data.socrata.com/api/views/9wfx-9qes/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Portland-Police-Bureau+mmpn-q6w2.csv https://moto.data.socrata.com/api/views/mmpn-q6w2/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Orlando-Police-Department+hirq-qvex.csv https://moto.data.socrata.com/api/views/hirq-qvex/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Roselle-Police-Department+gqz3-7kh6.csv https://moto.data.socrata.com/api/views/gqz3-7kh6/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Palm-Springs-Police-Department+evz7-c892.csv https://moto.data.socrata.com/api/views/evz7-c892/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Murrieta-Police-Department+p4kf-33nm.csv https://moto.data.socrata.com/api/views/p4kf-33nm/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Covina-Police-Department+ybye-xjrr.csv https://moto.data.socrata.com/api/views/ybye-xjrr/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/El-Dorado-County-Sheriff+aqj2-qp6f.csv https://moto.data.socrata.com/api/views/aqj2-qp6f/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Alpharetta-Public-Safety+qj3v-nk96.csv https://moto.data.socrata.com/api/views/qj3v-nk96/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/The-Dalles-Police-Department+viq6-py77.csv https://moto.data.socrata.com/api/views/viq6-py77/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Hemet-Police-Department+ura6-jy6v.csv https://moto.data.socrata.com/api/views/ura6-jy6v/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Benicia-Police-Department+bpgb-25dy.csv https://moto.data.socrata.com/api/views/bpgb-25dy/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Riverside-County-Sheriff-Department+2dfc-gktv.csv https://moto.data.socrata.com/api/views/2dfc-gktv/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Marana-Police-Department+cadr-he9e.csv https://moto.data.socrata.com/api/views/cadr-he9e/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Port-St-Lucie-Police-Department+k9v8-vh8y.csv https://moto.data.socrata.com/api/views/k9v8-vh8y/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Tavares-Police-Department+6tpd-det6.csv https://moto.data.socrata.com/api/views/6tpd-det6/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Benton-Police-Department+eg3r-eg8b.csv https://moto.data.socrata.com/api/views/eg3r-eg8b/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Monterey-County-Sheriff-s-Office+qc87-2rvn.csv https://moto.data.socrata.com/api/views/qc87-2rvn/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Sandy-Springs-Police-Department+nzaz-wj9p.csv https://moto.data.socrata.com/api/views/nzaz-wj9p/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Riverside-City-Police-Department+ui7x-bycv.csv https://moto.data.socrata.com/api/views/ui7x-bycv/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Los-Gatos-Monte-Sereno-Police-Department+w73q-hz3i.csv https://moto.data.socrata.com/api/views/w73q-hz3i/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Woodridge-Police-Department+2373-mhdj.csv https://moto.data.socrata.com/api/views/2373-mhdj/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Pensacola-Police-Department+vc6v-nqmb.csv https://moto.data.socrata.com/api/views/vc6v-nqmb/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Panama-City-Police-Department+mtwe-e9xp.csv https://moto.data.socrata.com/api/views/mtwe-e9xp/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Palo-Alto-Police-Department+dnen-xaab.csv https://moto.data.socrata.com/api/views/dnen-xaab/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Napa-Police-Department+ukqk-ax2k.csv https://moto.data.socrata.com/api/views/ukqk-ax2k/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Washington-DC+2vfk-6rp4.csv https://moto.data.socrata.com/api/views/2vfk-6rp4/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Elgin-Police-Department+wirm-wbhy.csv https://moto.data.socrata.com/api/views/wirm-wbhy/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Arvada-Police-Department+vh33-t5q4.csv https://moto.data.socrata.com/api/views/vh33-t5q4/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Stratford-Police-Department+ui29-mqcw.csv https://moto.data.socrata.com/api/views/ui29-mqcw/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Montgomery-County-Police-Department+sfk4-yjhw.csv https://moto.data.socrata.com/api/views/sfk4-yjhw/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Waukegan-Police+7eqd-4ng7.csv https://moto.data.socrata.com/api/views/7eqd-4ng7/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Pleasant-Hill-Police-Department+i8a5-7vrs.csv https://moto.data.socrata.com/api/views/i8a5-7vrs/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Oro-Valley-Police-Department+dg73-dzvm.csv https://moto.data.socrata.com/api/views/dg73-dzvm/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Kootenai-County-Sheriffs-Department+wx2b-gf3u.csv https://moto.data.socrata.com/api/views/wx2b-gf3u/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/El-Cerrito-Police-Department+a9zr-qcds.csv https://moto.data.socrata.com/api/views/a9zr-qcds/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Jacksonville-Police-Department+7pap-2yk6.csv https://moto.data.socrata.com/api/views/7pap-2yk6/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/St-Lucie-County-Sheriff+gqtc-erfg.csv https://moto.data.socrata.com/api/views/gqtc-erfg/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Queen-Anne-s-County-Sheriff-Office+sh7x-gbpf.csv https://moto.data.socrata.com/api/views/sh7x-gbpf/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Villa-Park-Police-Department+8pdu-z92b.csv https://moto.data.socrata.com/api/views/8pdu-z92b/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Union-City-Police-Department+xqci-zc8x.csv https://moto.data.socrata.com/api/views/xqci-zc8x/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Port-Orange-Police-Department+5fyw-hnz8.csv https://moto.data.socrata.com/api/views/5fyw-hnz8/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/North-Aurora-Police-Department+6wh3-2fnj.csv https://moto.data.socrata.com/api/views/6wh3-2fnj/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Cedar-Rapids+i4jc-nnwq.csv https://moto.data.socrata.com/api/views/i4jc-nnwq/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Alsip-Police-Department+vqpy-fgkn.csv https://moto.data.socrata.com/api/views/vqpy-fgkn/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Hammond-Police-Department+5eu3-nrsw.csv https://moto.data.socrata.com/api/views/5eu3-nrsw/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Hapeville-Police-Department+skue-xbmg.csv https://moto.data.socrata.com/api/views/skue-xbmg/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Douglasville-Police-Department+daww-n44p.csv https://moto.data.socrata.com/api/views/daww-n44p/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Tukwila-Police-Department+dzmm-nqfp.csv https://moto.data.socrata.com/api/views/dzmm-nqfp/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Ottawa-Police+uacw-px76.csv https://moto.data.socrata.com/api/views/uacw-px76/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Mountain-View-Police-Department+k56q-mt3c.csv https://moto.data.socrata.com/api/views/k56q-mt3c/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Fremont-Police-Department+nnzs-rxi5.csv https://moto.data.socrata.com/api/views/nnzs-rxi5/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Fairview-Heights-Police+ww4b-xkgx.csv https://moto.data.socrata.com/api/views/ww4b-xkgx/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Coeur-d-Alene-Police+a5ib-twvm.csv https://moto.data.socrata.com/api/views/a5ib-twvm/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Morgan-Hill-Police-Department+s9ji-4jh6.csv https://moto.data.socrata.com/api/views/s9ji-4jh6/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Paradise-Valley-Police-Department+4de7-admj.csv https://moto.data.socrata.com/api/views/4de7-admj/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Kingman-Police-Department+uxrf-mjbi.csv https://moto.data.socrata.com/api/views/uxrf-mjbi/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Decatur-Police-Department+bky9-42d6.csv https://moto.data.socrata.com/api/views/bky9-42d6/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Salinas-Police-Department+9gts-2xyn.csv https://moto.data.socrata.com/api/views/9gts-2xyn/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Sahuarita-Police-Department+kp85-v2y6.csv https://moto.data.socrata.com/api/views/kp85-v2y6/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Capitola-Police-Department+4tb3-9vya.csv https://moto.data.socrata.com/api/views/4tb3-9vya/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Bonner-County-Sheriffs-Office+8d97-xj4i.csv https://moto.data.socrata.com/api/views/8d97-xj4i/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Lafayette-Police-Department+bxwm-gjq4.csv https://moto.data.socrata.com/api/views/bxwm-gjq4/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Lantana-Police-Department+gf22-urzb.csv https://moto.data.socrata.com/api/views/gf22-urzb/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Flagstaff-Police-Department+2h4n-xivz.csv https://moto.data.socrata.com/api/views/2h4n-xivz/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Granite-City-Police-Department+j4xx-q7jw.csv https://moto.data.socrata.com/api/views/j4xx-q7jw/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Emeryville-Police-Department+icdc-r3z6.csv https://moto.data.socrata.com/api/views/icdc-r3z6/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/South-Gate-Police-Department+d642-5tug.csv https://moto.data.socrata.com/api/views/d642-5tug/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/ACCPD+8tt2-niit.csv https://moto.data.socrata.com/api/views/8tt2-niit/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Chamblee-Police-Department+kts8-f2hk.csv https://moto.data.socrata.com/api/views/kts8-f2hk/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Trumbull-Police-Department+5kae-n5jn.csv https://moto.data.socrata.com/api/views/5kae-n5jn/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/City-of-Beaumont-Police-Department+sg44-2pid.csv https://moto.data.socrata.com/api/views/sg44-2pid/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Newton-Police-Department+b6vd-4sjd.csv https://moto.data.socrata.com/api/views/b6vd-4sjd/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Brandon-Police+eykk-3wg4.csv https://moto.data.socrata.com/api/views/eykk-3wg4/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Darien+c84f-wxbb.csv https://moto.data.socrata.com/api/views/c84f-wxbb/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Eustis-Police-Department+au8g-2bds.csv https://moto.data.socrata.com/api/views/au8g-2bds/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Westfield-Police-Department+cnzt-czfs.csv https://moto.data.socrata.com/api/views/cnzt-czfs/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Buffalo-Police-Department+d5pr-6qjf.csv https://moto.data.socrata.com/api/views/d5pr-6qjf/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Newnan-Police-Department+ii2r-ey7u.csv https://moto.data.socrata.com/api/views/ii2r-ey7u/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Auburn-City-of+i6bg-57ig.csv https://moto.data.socrata.com/api/views/i6bg-57ig/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Dennis-Police-Department+8bkv-3u4h.csv https://moto.data.socrata.com/api/views/8bkv-3u4h/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Frederick-Police-Department+v4tj-cyi9.csv https://moto.data.socrata.com/api/views/v4tj-cyi9/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Urbandale-Police-Department+tsvc-udd5.csv https://moto.data.socrata.com/api/views/tsvc-udd5/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Federal-Way-Police-Department+y3sp-23na.csv https://moto.data.socrata.com/api/views/y3sp-23na/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Navajo-County-Sheriff-s-Office+txsk-vi4j.csv https://moto.data.socrata.com/api/views/txsk-vi4j/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Hopkinsville-Police-Department+v9fc-pj4e.csv https://moto.data.socrata.com/api/views/v9fc-pj4e/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Menlo-Park-Police-Department+ex86-feqy.csv https://moto.data.socrata.com/api/views/ex86-feqy/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Plano-Police-Department+jrat-ef37.csv https://moto.data.socrata.com/api/views/jrat-ef37/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Lake-Charles-Police-Department+3a3q-u43s.csv https://moto.data.socrata.com/api/views/3a3q-u43s/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Victoria-BC-Police-Department+f42u-v6f3.csv https://moto.data.socrata.com/api/views/f42u-v6f3/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Gulf-Shores-Police+fq2p-w7yu.csv https://moto.data.socrata.com/api/views/fq2p-w7yu/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Show-Low-Police-Department+6r32-4ssf.csv https://moto.data.socrata.com/api/views/6r32-4ssf/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Unified-Police-Department-of-Greater-Salt-Lake+wqfq-8svk.csv https://moto.data.socrata.com/api/views/wqfq-8svk/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Barnstable-Police-Department+9wyp-k94s.csv https://moto.data.socrata.com/api/views/9wyp-k94s/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Atlantic-Beach-Police-Department+brud-u4p7.csv https://moto.data.socrata.com/api/views/brud-u4p7/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Tucson-Police-Department+5e96-55x5.csv https://moto.data.socrata.com/api/views/5e96-55x5/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Cowley-County-Sheriff-s-Office+exq8-2wvg.csv https://moto.data.socrata.com/api/views/exq8-2wvg/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/North-Miami-Beach-Police+6ycu-kfnm.csv https://moto.data.socrata.com/api/views/6ycu-kfnm/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Alameda-County-Sheriff-s-Office+bvi2-5rde.csv https://moto.data.socrata.com/api/views/bvi2-5rde/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Renton-City-of+eb8c-wrfi.csv https://moto.data.socrata.com/api/views/eb8c-wrfi/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Halton-Regional-Police-Service+qsub-ypin.csv https://moto.data.socrata.com/api/views/qsub-ypin/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Marion-County-Sheriff-s-Office+dscn-gw5y.csv https://moto.data.socrata.com/api/views/dscn-gw5y/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/University-of-California-Davis-Police-Department+vnws-nn3h.csv https://moto.data.socrata.com/api/views/vnws-nn3h/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/St-Mary-s-County-Sheriff-s-Office+sh33-yisj.csv https://moto.data.socrata.com/api/views/sh33-yisj/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Salt-Lake-City-Police-Department+qbr3-v7gz.csv https://moto.data.socrata.com/api/views/qbr3-v7gz/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Fort-Bragg-Police-Department+8hud-eimd.csv https://moto.data.socrata.com/api/views/8hud-eimd/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Lafayette-Police-Department+sz4k-2wja.csv https://moto.data.socrata.com/api/views/sz4k-2wja/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Johns-Creek-Police-Department+ac24-ubgm.csv https://moto.data.socrata.com/api/views/ac24-ubgm/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Lakewood-Police-Department+v76p-ut9w.csv https://moto.data.socrata.com/api/views/v76p-ut9w/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Natchitoches-Police-Department+cxkg-rdj3.csv https://moto.data.socrata.com/api/views/cxkg-rdj3/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Lady-Lake-Police-Department+nxiz-9b9p.csv https://moto.data.socrata.com/api/views/nxiz-9b9p/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Oakdale-Police-Department+4k6m-tuew.csv https://moto.data.socrata.com/api/views/4k6m-tuew/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Roseville-Police-Department+268s-g4ug.csv https://moto.data.socrata.com/api/views/268s-g4ug/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Murray-Police-Department+qyw2-2fgm.csv https://moto.data.socrata.com/api/views/qyw2-2fgm/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/San-Pablo-Police-Department+tsdt-igxn.csv https://moto.data.socrata.com/api/views/tsdt-igxn/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Greenfield-Police-Department+8ed7-i7dj.csv https://moto.data.socrata.com/api/views/8ed7-i7dj/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Bell-Gardens-Police-Department+qk4g-6hss.csv https://moto.data.socrata.com/api/views/qk4g-6hss/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Harrisonburg-Police-Dept-+iik4-zz4b.csv https://moto.data.socrata.com/api/views/iik4-zz4b/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Lake-Forest-Park-Police-Department+4wpa-8chf.csv https://moto.data.socrata.com/api/views/4wpa-8chf/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Kansas-City-Police-Department+6vhr-dqzs.csv https://moto.data.socrata.com/api/views/6vhr-dqzs/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Washington-County-Sheriff-s-Office+3gpk-u8yy.csv https://moto.data.socrata.com/api/views/3gpk-u8yy/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Vermont-State-Police+95vx-m9x8.csv https://moto.data.socrata.com/api/views/95vx-m9x8/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Lilburn-Police-Department+e63r-zqtz.csv https://moto.data.socrata.com/api/views/e63r-zqtz/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/City-of-Madison+dddr-t8pv.csv https://moto.data.socrata.com/api/views/dddr-t8pv/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Lewisville-Police-Department+jy42-8kka.csv https://moto.data.socrata.com/api/views/jy42-8kka/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Reno-Police-Department+hisp-5yqz.csv https://moto.data.socrata.com/api/views/hisp-5yqz/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Albany-CA-Police-Department+n5yu-6kr8.csv https://moto.data.socrata.com/api/views/n5yu-6kr8/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Jacksonville-Police-Department+uxk8-mump.csv https://moto.data.socrata.com/api/views/uxk8-mump/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Solano-County-Sheriff-s-Office+6sun-2h3n.csv https://moto.data.socrata.com/api/views/6sun-2h3n/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Fort-Pierce-Police-Department+5ivr-afst.csv https://moto.data.socrata.com/api/views/5ivr-afst/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Oviedo-Police-Department+braw-rz5i.csv https://moto.data.socrata.com/api/views/braw-rz5i/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Sierra-Madre-Police-Department+i94b-hxdy.csv https://moto.data.socrata.com/api/views/i94b-hxdy/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Salem-OR-Police-Department+9daj-ackw.csv https://moto.data.socrata.com/api/views/9daj-ackw/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/University-of-Wisconsin-Madison-Police-Department+3hsu-9f9k.csv https://moto.data.socrata.com/api/views/3hsu-9f9k/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Waterford-Police-Department+jp4p-y9zx.csv https://moto.data.socrata.com/api/views/jp4p-y9zx/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Jackson-Police-Department+27jd-342s.csv https://moto.data.socrata.com/api/views/27jd-342s/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Port-Wentworth-Police-Department+e6h3-unsh.csv https://moto.data.socrata.com/api/views/e6h3-unsh/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Washington-County-Sheriffs-Office+vafb-s5i2.csv https://moto.data.socrata.com/api/views/vafb-s5i2/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Clanton-Police-Department+kdwz-usqz.csv https://moto.data.socrata.com/api/views/kdwz-usqz/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Lakewood-Police-Department+jkax-f3xp.csv https://moto.data.socrata.com/api/views/jkax-f3xp/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Greenfield-Police-Department+r9qj-rrdq.csv https://moto.data.socrata.com/api/views/r9qj-rrdq/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Tulare-Police-Department+4hrs-s78v.csv https://moto.data.socrata.com/api/views/4hrs-s78v/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Summit-County-Sheriffs-Office+99s7-nb8v.csv https://moto.data.socrata.com/api/views/99s7-nb8v/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Harford-County-Sheriff-s-Office+qfdb-58dd.csv https://moto.data.socrata.com/api/views/qfdb-58dd/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Hoke-County-Sheriffs-Office+if6r-65cf.csv https://moto.data.socrata.com/api/views/if6r-65cf/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Lyndhurst-Police-Department+ka3i-mmzb.csv https://moto.data.socrata.com/api/views/ka3i-mmzb/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Muskogee-Police-Department+uc6t-z4kx.csv https://moto.data.socrata.com/api/views/uc6t-z4kx/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/DeSoto-County-Sheriff-s-Office+qibh-mi7v.csv https://moto.data.socrata.com/api/views/qibh-mi7v/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Town-of-Greece-Police-Department+ter5-gmgn.csv https://moto.data.socrata.com/api/views/ter5-gmgn/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Windsor-Police-Service+wa9g-iumt.csv https://moto.data.socrata.com/api/views/wa9g-iumt/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Hendersonville-Police-Department+hurc-gkur.csv https://moto.data.socrata.com/api/views/hurc-gkur/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Westwood-Police-Department+pnr4-833s.csv https://moto.data.socrata.com/api/views/pnr4-833s/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Whittier-Police-Department-Santa-Fe-Springs+gkcg-shwz.csv https://moto.data.socrata.com/api/views/gkcg-shwz/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Westminster-Police-Department-MD-+fq75-6zte.csv https://moto.data.socrata.com/api/views/fq75-6zte/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Alexander-City-Police-Department+hba7-qpbk.csv https://moto.data.socrata.com/api/views/hba7-qpbk/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Lethbridge-Regional-Police-Service+rsp4-a9ym.csv https://moto.data.socrata.com/api/views/rsp4-a9ym/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Aransas-Pass-Police-Department+sf4y-xsgd.csv https://moto.data.socrata.com/api/views/sf4y-xsgd/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Delaware-Police-Department-OH-+89ra-nsqf.csv https://moto.data.socrata.com/api/views/89ra-nsqf/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Garland-Police-Department+gnnd-dfiz.csv https://moto.data.socrata.com/api/views/gnnd-dfiz/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Euless-Police-Department+75nm-6ye6.csv https://moto.data.socrata.com/api/views/75nm-6ye6/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Sheridan-Police-Department+n4x5-bt6p.csv https://moto.data.socrata.com/api/views/n4x5-bt6p/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Arlington-Police-Department+d23e-gtaf.csv https://moto.data.socrata.com/api/views/d23e-gtaf/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/West-Lafayette-Police-Dept+meth-bc52.csv https://moto.data.socrata.com/api/views/meth-bc52/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Worthington-Division-of-Police+3qct-9v97.csv https://moto.data.socrata.com/api/views/3qct-9v97/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Scranton-Police-Department+wkxj-c4j2.csv https://moto.data.socrata.com/api/views/wkxj-c4j2/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Lincoln-County-Sheriff-s-Office+tve5-aitk.csv https://moto.data.socrata.com/api/views/tve5-aitk/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Belmont-Police-Department+2xyt-mv4j.csv https://moto.data.socrata.com/api/views/2xyt-mv4j/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Aberdeen-WA-Police-Department+qk26-gmnq.csv https://moto.data.socrata.com/api/views/qk26-gmnq/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Grapevine-Police-Department+y382-iuvq.csv https://moto.data.socrata.com/api/views/y382-iuvq/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/University-of-Florida-Police-Department+iby6-7naf.csv https://moto.data.socrata.com/api/views/iby6-7naf/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Warwick-Police-Department+hsvu-ayqk.csv https://moto.data.socrata.com/api/views/hsvu-ayqk/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Norcross-Police-Department+a774-iija.csv https://moto.data.socrata.com/api/views/a774-iija/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Marathon-County+e3aw-765x.csv https://moto.data.socrata.com/api/views/e3aw-765x/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Greenwood-County-Sheriff-s-Office+dws6-2ehd.csv https://moto.data.socrata.com/api/views/dws6-2ehd/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Maryville-Police-Department+yv2f-s79q.csv https://moto.data.socrata.com/api/views/yv2f-s79q/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Kilgore-Police-Department+enw3-q549.csv https://moto.data.socrata.com/api/views/enw3-q549/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Blount-County-Sheriffs-Office+wcdb-uwd3.csv https://moto.data.socrata.com/api/views/wcdb-uwd3/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Andalusia-Police-Department+qn2i-kxib.csv https://moto.data.socrata.com/api/views/qn2i-kxib/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Rowlett-Police-Department+xjga-i98z.csv https://moto.data.socrata.com/api/views/xjga-i98z/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Sevier-County-Sheriff-s-Office+72jh-ng3b.csv https://moto.data.socrata.com/api/views/72jh-ng3b/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Loudoun-County-Sheriff-s-Office+wxnp-mb4p.csv https://moto.data.socrata.com/api/views/wxnp-mb4p/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Washington-City-Police-Department+hdve-4ade.csv https://moto.data.socrata.com/api/views/hdve-4ade/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Juab-County-Sheriff-s-Office+jjrj-nk8q.csv https://moto.data.socrata.com/api/views/jjrj-nk8q/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Mount-Rainier-Police-Department+ita7-3u78.csv https://moto.data.socrata.com/api/views/ita7-3u78/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Draper-Police-Department+bzjh-7c9q.csv https://moto.data.socrata.com/api/views/bzjh-7c9q/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/South-Jordan-Police-Department+b68b-9m49.csv https://moto.data.socrata.com/api/views/b68b-9m49/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Perry-Police-Department+6tnu-5k6s.csv https://moto.data.socrata.com/api/views/6tnu-5k6s/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/St-George-Police-Department+b6ad-s65z.csv https://moto.data.socrata.com/api/views/b6ad-s65z/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Burlington-Police+rzw6-wxvi.csv https://moto.data.socrata.com/api/views/rzw6-wxvi/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Newport-Police-Department+akvm-dr2a.csv https://moto.data.socrata.com/api/views/akvm-dr2a/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/LaGrange-GA-Police-Department+fzra-fqtw.csv https://moto.data.socrata.com/api/views/fzra-fqtw/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Amherst-Police-Department+g3zy-sef9.csv https://moto.data.socrata.com/api/views/g3zy-sef9/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Tooele-City-Police-Department+i6m8-9473.csv https://moto.data.socrata.com/api/views/i6m8-9473/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Yakima-County-Sheriff+fq8f-gsdd.csv https://moto.data.socrata.com/api/views/fq8f-gsdd/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Piedmont-Police-Department+p52h-m2j9.csv https://moto.data.socrata.com/api/views/p52h-m2j9/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Rockport-Police-Department+iiz5-97r4.csv https://moto.data.socrata.com/api/views/iiz5-97r4/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Westfield-Police-Department+ywii-22g6.csv https://moto.data.socrata.com/api/views/ywii-22g6/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Carbondale-Police-Department+fn2y-b9hq.csv https://moto.data.socrata.com/api/views/fn2y-b9hq/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Appanoose-County-Sheriff+adqx-ug73.csv https://moto.data.socrata.com/api/views/adqx-ug73/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Fayetteville-Police-Department+typ3-2qhd.csv https://moto.data.socrata.com/api/views/typ3-2qhd/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Washington-County-Sheriff-s-Office+p948-sxc9.csv https://moto.data.socrata.com/api/views/p948-sxc9/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Charles-County-Sheriff+ei6h-y7dq.csv https://moto.data.socrata.com/api/views/ei6h-y7dq/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/West-Warwick-Police-Department+sdgf-tnhm.csv https://moto.data.socrata.com/api/views/sdgf-tnhm/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Kodiak-Police-Department+vt5r-img2.csv https://moto.data.socrata.com/api/views/vt5r-img2/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Cheektowaga-Town-Police-Department+qbeq-u3ix.csv https://moto.data.socrata.com/api/views/qbeq-u3ix/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Greenwood-Police-Department-SC-+qgng-4qk3.csv https://moto.data.socrata.com/api/views/qgng-4qk3/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Rose-Hill-Police-Department+v4z7-nmqn.csv https://moto.data.socrata.com/api/views/v4z7-nmqn/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Cape-Coral-Police-Department+25yj-aejd.csv https://moto.data.socrata.com/api/views/25yj-aejd/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Yakima-Police-Department-WA-+xny3-tbqi.csv https://moto.data.socrata.com/api/views/xny3-tbqi/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Hendersonville-Police+qhc8-92ry.csv https://moto.data.socrata.com/api/views/qhc8-92ry/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Plymouth-Township-Police+4dzg-ka3b.csv https://moto.data.socrata.com/api/views/4dzg-ka3b/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Holyoke-Police-Department+jsmq-3qke.csv https://moto.data.socrata.com/api/views/jsmq-3qke/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Webster-Police-Department+ahw7-gyig.csv https://moto.data.socrata.com/api/views/ahw7-gyig/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Prince-Georges-County-Police-Department+893p-dsaz.csv https://moto.data.socrata.com/api/views/893p-dsaz/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Marina-Police-Department+8a5c-f5jq.csv https://moto.data.socrata.com/api/views/8a5c-f5jq/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Salem-UT-Police-Department+5frh-rghv.csv https://moto.data.socrata.com/api/views/5frh-rghv/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Plaquemines-Parish-Sheriff-s-Office+9898-hy7f.csv https://moto.data.socrata.com/api/views/9898-hy7f/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Lehi-Police-Department+vzxf-zjrz.csv https://moto.data.socrata.com/api/views/vzxf-zjrz/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/South-Salt-Lake-Police-Department+iem8-u8t7.csv https://moto.data.socrata.com/api/views/iem8-u8t7/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Ellensburg-Police-Department+x75f-j85p.csv https://moto.data.socrata.com/api/views/x75f-j85p/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Ivins-Police-Department+755z-96e9.csv https://moto.data.socrata.com/api/views/755z-96e9/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Provo-Police-Department+b6rh-7mdy.csv https://moto.data.socrata.com/api/views/b6rh-7mdy/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/San-Angelo-Police-Department+g8bq-zvaf.csv https://moto.data.socrata.com/api/views/g8bq-zvaf/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Dunwoody-Police+nn2g-zfks.csv https://moto.data.socrata.com/api/views/nn2g-zfks/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Hampton-Police-Department+pwqw-9u3z.csv https://moto.data.socrata.com/api/views/pwqw-9u3z/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Eugene-Police-Department+56e2-jw9g.csv https://moto.data.socrata.com/api/views/56e2-jw9g/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Junction-City-Police-Department+mq37-77ch.csv https://moto.data.socrata.com/api/views/mq37-77ch/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Georgia-Institute-of-Technology+nd8h-v3b5.csv https://moto.data.socrata.com/api/views/nd8h-v3b5/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Opelousas-Police-Department+fgy6-9v23.csv https://moto.data.socrata.com/api/views/fgy6-9v23/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Laurel-Police-Department+mund-uxd9.csv https://moto.data.socrata.com/api/views/mund-uxd9/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Mint-Hill-Police-Department+nkhn-fxkg.csv https://moto.data.socrata.com/api/views/nkhn-fxkg/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Brown-County-Sheriff-s-Office+pm6h-iycp.csv https://moto.data.socrata.com/api/views/pm6h-iycp/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Santa-Fe-County-Sheriff-s-Office+sf3a-evcx.csv https://moto.data.socrata.com/api/views/sf3a-evcx/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/San-Leandro-Police-Department+6nbc-apvm.csv https://moto.data.socrata.com/api/views/6nbc-apvm/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/University-of-Georgia-Police-Department+96mv-ny7d.csv https://moto.data.socrata.com/api/views/96mv-ny7d/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Polk-County-Sheriffs-Office+2cje-6qnt.csv https://moto.data.socrata.com/api/views/2cje-6qnt/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Edinburg-Police-Department+3fsz-h5nj.csv https://moto.data.socrata.com/api/views/3fsz-h5nj/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Norwood-Police-Department+gdna-ibyy.csv https://moto.data.socrata.com/api/views/gdna-ibyy/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Bourbon-County-Sheriff-s-Office+w6z4-tcg4.csv https://moto.data.socrata.com/api/views/w6z4-tcg4/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Miami-Springs-Police-Dept+biz7-rwwj.csv https://moto.data.socrata.com/api/views/biz7-rwwj/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Louisiana-State-University+3y34-gc9j.csv https://moto.data.socrata.com/api/views/3y34-gc9j/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Charlotte-County-Sheriffs-Office+7ypp-i6iw.csv https://moto.data.socrata.com/api/views/7ypp-i6iw/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Woods-Cross-Police-Department+uwi2-tj2z.csv https://moto.data.socrata.com/api/views/uwi2-tj2z/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Cannon-Falls-Police-Department+a955-affm.csv https://moto.data.socrata.com/api/views/a955-affm/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Lawton-Police-Department+93v7-jepz.csv https://moto.data.socrata.com/api/views/93v7-jepz/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Dixie-College+raex-q7kp.csv https://moto.data.socrata.com/api/views/raex-q7kp/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/West-Linn-Police-Department+y82v-j9cz.csv https://moto.data.socrata.com/api/views/y82v-j9cz/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Keller-Police-Department+hkdh-9w2h.csv https://moto.data.socrata.com/api/views/hkdh-9w2h/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Niles-Police-Department+35hz-p6dg.csv https://moto.data.socrata.com/api/views/35hz-p6dg/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Hartsville-Police-Department+tyej-zxkx.csv https://moto.data.socrata.com/api/views/tyej-zxkx/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Belle-Meade-Police-Department+ajcu-avs6.csv https://moto.data.socrata.com/api/views/ajcu-avs6/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Kent-County-Sheriff-s-Office+2dg7-6s4z.csv https://moto.data.socrata.com/api/views/2dg7-6s4z/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/St-Petersburg-Police-Department+7j4g-gvd7.csv https://moto.data.socrata.com/api/views/7j4g-gvd7/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Blendon-Township-Police-Department+4mzf-syp6.csv https://moto.data.socrata.com/api/views/4mzf-syp6/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Fort-Worth-Police-Department+kvw2-cmwp.csv https://moto.data.socrata.com/api/views/kvw2-cmwp/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Bell-Police-Department+bi3c-cw2b.csv https://moto.data.socrata.com/api/views/bi3c-cw2b/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Wayne-County-Sheriff-s-Office+4isd-bcq5.csv https://moto.data.socrata.com/api/views/4isd-bcq5/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/University-of-Texas-Arlington+8s5x-iedj.csv https://moto.data.socrata.com/api/views/8s5x-iedj/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Ridgely-Police-Department+f7ie-msjz.csv https://moto.data.socrata.com/api/views/f7ie-msjz/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Division-of-Capitol-Police+8q4e-zcd5.csv https://moto.data.socrata.com/api/views/8q4e-zcd5/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Rochester-City-Police-Department+65ke-36e8.csv https://moto.data.socrata.com/api/views/65ke-36e8/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Brigham-City-Police-Department+t55s-hwrt.csv https://moto.data.socrata.com/api/views/t55s-hwrt/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Greenbelt-Police-Department+uzsm-dzk6.csv https://moto.data.socrata.com/api/views/uzsm-dzk6/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/La-Verkin-City-Police-Department+bjzk-jqsn.csv https://moto.data.socrata.com/api/views/bjzk-jqsn/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Maryland-Heights-Police-Department+5yhv-cgu7.csv https://moto.data.socrata.com/api/views/5yhv-cgu7/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Toppenish-Police-Department+u8f9-p3fi.csv https://moto.data.socrata.com/api/views/u8f9-p3fi/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Elyria-Police-Department+a4au-q335.csv https://moto.data.socrata.com/api/views/a4au-q335/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/City-of-Middletown-Police-Department+9iyd-za7e.csv https://moto.data.socrata.com/api/views/9iyd-za7e/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Grandview-Police-Department+4bya-2ifd.csv https://moto.data.socrata.com/api/views/4bya-2ifd/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/North-Bay-Village-Police+5w7u-7cyf.csv https://moto.data.socrata.com/api/views/5w7u-7cyf/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Leesburg-Police-Department+criy-sikb.csv https://moto.data.socrata.com/api/views/criy-sikb/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Beaver-County-Sheriff-s-Office+ydmh-g38z.csv https://moto.data.socrata.com/api/views/ydmh-g38z/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Lincoln-County-S-O-+dg6a-qs7x.csv https://moto.data.socrata.com/api/views/dg6a-qs7x/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Tacoma-Police-Department+8vq8-27ge.csv https://moto.data.socrata.com/api/views/8vq8-27ge/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Surfside-Police-Department+cs3j-ahw2.csv https://moto.data.socrata.com/api/views/cs3j-ahw2/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Key-Biscayne-Police-Department+c6b5-72q8.csv https://moto.data.socrata.com/api/views/c6b5-72q8/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/University-Park-Police-Department+i2ac-7qbz.csv https://moto.data.socrata.com/api/views/i2ac-7qbz/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Fresno-Police-Department+c943-w8up.csv https://moto.data.socrata.com/api/views/c943-w8up/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Picayune-Police-Department+p7tq-nf5k.csv https://moto.data.socrata.com/api/views/p7tq-nf5k/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Cottage-Grove-Police-Department+hxrn-h2an.csv https://moto.data.socrata.com/api/views/hxrn-h2an/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Monroe-Police-Department+hexc-j43p.csv https://moto.data.socrata.com/api/views/hexc-j43p/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/El-Paso-County-Sheriff-s-Office+2v7c-3axy.csv https://moto.data.socrata.com/api/views/2v7c-3axy/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Des-Moines-Police-Department+n2p9-rjjx.csv https://moto.data.socrata.com/api/views/n2p9-rjjx/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Astoria-Police-Department+r84j-nf34.csv https://moto.data.socrata.com/api/views/r84j-nf34/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Stayton-Police-Department+pxtu-6tyc.csv https://moto.data.socrata.com/api/views/pxtu-6tyc/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Abbotsford-Police-Department+pqhw-v8xn.csv https://moto.data.socrata.com/api/views/pqhw-v8xn/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Appleton-Police-Department+c4nf-nb7p.csv https://moto.data.socrata.com/api/views/c4nf-nb7p/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Hagerstown-Police-Department+xwsq-rdqe.csv https://moto.data.socrata.com/api/views/xwsq-rdqe/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Ashland-Police-Department+r4fp-j8h5.csv https://moto.data.socrata.com/api/views/r4fp-j8h5/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Wolf-Point-Police-Department+hjsr-j4gv.csv https://moto.data.socrata.com/api/views/hjsr-j4gv/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Okaloosa-County-Sheriff-s-Office+7kyy-jjvv.csv https://moto.data.socrata.com/api/views/7kyy-jjvv/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/University-of-Cincinnati+hs2a-ks74.csv https://moto.data.socrata.com/api/views/hs2a-ks74/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Upper-Gwynedd-Township-Police+8zne-jss7.csv https://moto.data.socrata.com/api/views/8zne-jss7/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Nash-County+3zy9-5gau.csv https://moto.data.socrata.com/api/views/3zy9-5gau/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Kentwood-Police-Department+5947-dwi6.csv https://moto.data.socrata.com/api/views/5947-dwi6/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Jackson-County-Sheriff-s-Office+eqwe-xnen.csv https://moto.data.socrata.com/api/views/eqwe-xnen/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Union-Gap-Police-Department+qqt7-hwkt.csv https://moto.data.socrata.com/api/views/qqt7-hwkt/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Mason-County-Sheriffs-Office+bg2i-yi3u.csv https://moto.data.socrata.com/api/views/bg2i-yi3u/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Farmington-Police-Department+jxwv-wy9e.csv https://moto.data.socrata.com/api/views/jxwv-wy9e/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Nephi-City+furh-3bsf.csv https://moto.data.socrata.com/api/views/furh-3bsf/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Signal-Hill-Police-Department+mt9f-tfvu.csv https://moto.data.socrata.com/api/views/mt9f-tfvu/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Southlake-Department-of-Public-Safety+m784-r37z.csv https://moto.data.socrata.com/api/views/m784-r37z/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Price-City-Police-Department+q4sb-ackj.csv https://moto.data.socrata.com/api/views/q4sb-ackj/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Coshocton-County-Sheriffs-Office+a2mw-fhiy.csv https://moto.data.socrata.com/api/views/a2mw-fhiy/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Edina-Police-Department+ai49-dkmn.csv https://moto.data.socrata.com/api/views/ai49-dkmn/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/East-Grand-Rapids-Department-of-Public-Safety+s69z-3mci.csv https://moto.data.socrata.com/api/views/s69z-3mci/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Trotwood-Police-Department+ct5j-yhr8.csv https://moto.data.socrata.com/api/views/ct5j-yhr8/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Healdsburg-Police-Department+apti-wnku.csv https://moto.data.socrata.com/api/views/apti-wnku/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/University-of-Virginia+22ee-5zkz.csv https://moto.data.socrata.com/api/views/22ee-5zkz/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Santa-Cruz-County-Sheriffs-Office+mfg4-gpqr.csv https://moto.data.socrata.com/api/views/mfg4-gpqr/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Martinez-Police-Department+vpaa-2jww.csv https://moto.data.socrata.com/api/views/vpaa-2jww/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Eureka-Police-Department+mum2-khni.csv https://moto.data.socrata.com/api/views/mum2-khni/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Towson-University-Police-Department+mp9g-k2zv.csv https://moto.data.socrata.com/api/views/mp9g-k2zv/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Liberty-Police+szzm-pfid.csv https://moto.data.socrata.com/api/views/szzm-pfid/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Eastern-Pike-Regional-Police-Department+d2fc-hh5x.csv https://moto.data.socrata.com/api/views/d2fc-hh5x/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Yarmouth-Police-Department+33pn-qe25.csv https://moto.data.socrata.com/api/views/33pn-qe25/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Wilmore-Police-Department+2vaj-asct.csv https://moto.data.socrata.com/api/views/2vaj-asct/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Saratoga-Springs-Police-Department+6yaa-r3j7.csv https://moto.data.socrata.com/api/views/6yaa-r3j7/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Syracuse-Police-Department+ghjp-49ua.csv https://moto.data.socrata.com/api/views/ghjp-49ua/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Orem-Police-Department+s9ax-xnsb.csv https://moto.data.socrata.com/api/views/s9ax-xnsb/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Wasatch-County-Sheriff-s-Office+k43k-pau8.csv https://moto.data.socrata.com/api/views/k43k-pau8/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Moorestown-Township-Police-Department+vfih-sbr3.csv https://moto.data.socrata.com/api/views/vfih-sbr3/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Davis-County-Sheriff-s-Office+6zfn-q3zf.csv https://moto.data.socrata.com/api/views/6zfn-q3zf/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Mapleton-City-Police-Department+xvt5-dynb.csv https://moto.data.socrata.com/api/views/xvt5-dynb/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Sunset-Police-Department+ftyc-un2m.csv https://moto.data.socrata.com/api/views/ftyc-un2m/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Los-Altos-Police-Department+bt3a-mvjj.csv https://moto.data.socrata.com/api/views/bt3a-mvjj/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Springdale-Department-of-Public-Safety+ib3s-yvys.csv https://moto.data.socrata.com/api/views/ib3s-yvys/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Riverdale-Park-Police-Department+86gs-jt4z.csv https://moto.data.socrata.com/api/views/86gs-jt4z/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Salisbury-Police-Department+4wek-5kq7.csv https://moto.data.socrata.com/api/views/4wek-5kq7/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Utah-County-Sheriff-s-Office+7kva-83q3.csv https://moto.data.socrata.com/api/views/7kva-83q3/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Sanford-Police-Department+xuer-5mq6.csv https://moto.data.socrata.com/api/views/xuer-5mq6/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Pleasant-Grove-Police-Department+qp99-5rwg.csv https://moto.data.socrata.com/api/views/qp99-5rwg/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/North-Richland-Hills-Police-Department+iffq-gb3n.csv https://moto.data.socrata.com/api/views/iffq-gb3n/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Prince-Georges-Community-College-Campus-Police+f882-ekjn.csv https://moto.data.socrata.com/api/views/f882-ekjn/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Joplin-Police-Department+wjvx-nht8.csv https://moto.data.socrata.com/api/views/wjvx-nht8/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Riverside-Department-of-Public-Safety+ths2-eq4j.csv https://moto.data.socrata.com/api/views/ths2-eq4j/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Delray-Beach-Police-Department+ub3s-nu4t.csv https://moto.data.socrata.com/api/views/ub3s-nu4t/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Keizer-Police-Department+22fg-e72j.csv https://moto.data.socrata.com/api/views/22fg-e72j/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Paris-Police-Department+69nv-xqjx.csv https://moto.data.socrata.com/api/views/69nv-xqjx/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Lindon-City-Police-Department+wnjb-jp7t.csv https://moto.data.socrata.com/api/views/wnjb-jp7t/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Monmouth-Police-Department+u8nw-djma.csv https://moto.data.socrata.com/api/views/u8nw-djma/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Lincoln-City-OR-Police-Department+j239-rf66.csv https://moto.data.socrata.com/api/views/j239-rf66/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Iredell-County-Sheriff-s-Office+f424-nqrx.csv https://moto.data.socrata.com/api/views/f424-nqrx/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Aumsville-Police-Department+gske-muzd.csv https://moto.data.socrata.com/api/views/gske-muzd/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Dallas-OR-Police-Department+jf5h-658h.csv https://moto.data.socrata.com/api/views/jf5h-658h/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Dublin-Police-Services+ifng-r995.csv https://moto.data.socrata.com/api/views/ifng-r995/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Port-Jervis-Police-Department+m2fn-m8mm.csv https://moto.data.socrata.com/api/views/m2fn-m8mm/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Tualatin-Police-Department+pvua-bfus.csv https://moto.data.socrata.com/api/views/pvua-bfus/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Rockwall-Police-Department+54zr-v9y3.csv https://moto.data.socrata.com/api/views/54zr-v9y3/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Tieton-Police-Department+sxdy-f77u.csv https://moto.data.socrata.com/api/views/sxdy-f77u/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Lower-Township-Police-Department+vdxy-akyi.csv https://moto.data.socrata.com/api/views/vdxy-akyi/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Centralia-Police-Department+bhjr-i88p.csv https://moto.data.socrata.com/api/views/bhjr-i88p/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Plainfield-Police-Department+54hs-uhun.csv https://moto.data.socrata.com/api/views/54hs-uhun/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Wapato-Police-Department+s9p9-b7v4.csv https://moto.data.socrata.com/api/views/s9p9-b7v4/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Derry-Township+2ynb-bcau.csv https://moto.data.socrata.com/api/views/2ynb-bcau/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/The-University-of-Arizona-Police-Department+tg4d-cwgz.csv https://moto.data.socrata.com/api/views/tg4d-cwgz/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Sand-Springs-Police-Department+u6gp-u77e.csv https://moto.data.socrata.com/api/views/u6gp-u77e/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Lakeport-Police-Department+j99t-nuha.csv https://moto.data.socrata.com/api/views/j99t-nuha/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Sumner-Police-Department+ba2t-rw4i.csv https://moto.data.socrata.com/api/views/ba2t-rw4i/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Cottonwood-Heights-Police-Department+f36u-3j9p.csv https://moto.data.socrata.com/api/views/f36u-3j9p/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Pearland-Police-Department+dcd7-sq3z.csv https://moto.data.socrata.com/api/views/dcd7-sq3z/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Kingston-Police+fjwd-syvh.csv https://moto.data.socrata.com/api/views/fjwd-syvh/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Collier-County-Sheriff-s-Office+a6t8-qi8u.csv https://moto.data.socrata.com/api/views/a6t8-qi8u/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Middletown-Township-Police-Department+ehkt-fukk.csv https://moto.data.socrata.com/api/views/ehkt-fukk/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/The-Colony-Police-Department+eexh-n73i.csv https://moto.data.socrata.com/api/views/eexh-n73i/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Richmond-Hill-Police-Department+htmv-35st.csv https://moto.data.socrata.com/api/views/htmv-35st/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Utah-Valley-University-Police+pjz3-fsj7.csv https://moto.data.socrata.com/api/views/pjz3-fsj7/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Willard-Police-Department+eh7u-6c6f.csv https://moto.data.socrata.com/api/views/eh7u-6c6f/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Gloucester-County-Sheriffs-Department+p22d-mad3.csv https://moto.data.socrata.com/api/views/p22d-mad3/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Gun-Barrel-City-Police-Department+xciu-hazf.csv https://moto.data.socrata.com/api/views/xciu-hazf/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/North-Carolina-State-University-Police-Department+w4bu-k5fr.csv https://moto.data.socrata.com/api/views/w4bu-k5fr/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Brevard-Police-Department+mpph-w42x.csv https://moto.data.socrata.com/api/views/mpph-w42x/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Alcoa-Police-Department+e3ja-a2wh.csv https://moto.data.socrata.com/api/views/e3ja-a2wh/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Webster-Groves-Police-Department+eshh-ujr9.csv https://moto.data.socrata.com/api/views/eshh-ujr9/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Sheridan-Police-Department+f83m-659q.csv https://moto.data.socrata.com/api/views/f83m-659q/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Worcester-Police-Department+jfwn-iu5d.csv https://moto.data.socrata.com/api/views/jfwn-iu5d/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Red-Oak-Police-Department+gj2j-z5cv.csv https://moto.data.socrata.com/api/views/gj2j-z5cv/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Gunnison-Police-Department+vs8d-itce.csv https://moto.data.socrata.com/api/views/vs8d-itce/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Haverford-Township-Police-Department+9tad-g4i3.csv https://moto.data.socrata.com/api/views/9tad-g4i3/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Selah-Police-Department-WA-+tjqz-cdi8.csv https://moto.data.socrata.com/api/views/tjqz-cdi8/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Lone-Peak-Police-Department+f3um-xiwz.csv https://moto.data.socrata.com/api/views/f3um-xiwz/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Grand-Ronde+vims-jcpu.csv https://moto.data.socrata.com/api/views/vims-jcpu/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Leon-Valley-Police-Department+23ix-wnzz.csv https://moto.data.socrata.com/api/views/23ix-wnzz/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Yamhill-County-Sheriff-s-Office+fa3h-43bg.csv https://moto.data.socrata.com/api/views/fa3h-43bg/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Owasso-Police-Department+wsay-6a3p.csv https://moto.data.socrata.com/api/views/wsay-6a3p/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Santa-Clara-Police-Department+8jdb-tnnf.csv https://moto.data.socrata.com/api/views/8jdb-tnnf/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Pueblo-County-Sheriff-s-Office+uw9i-3pa7.csv https://moto.data.socrata.com/api/views/uw9i-3pa7/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Nassau-Bay-Police-Department+ubqp-qrwd.csv https://moto.data.socrata.com/api/views/ubqp-qrwd/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Mabank-Police-Department+wz2k-vt53.csv https://moto.data.socrata.com/api/views/wz2k-vt53/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Maize-Police-Department+xnji-hibw.csv https://moto.data.socrata.com/api/views/xnji-hibw/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/O-Fallon-Police-Department+yiyw-xqw5.csv https://moto.data.socrata.com/api/views/yiyw-xqw5/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Naples+rabw-3qz3.csv https://moto.data.socrata.com/api/views/rabw-3qz3/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Cass-County-Sheriff-s-Office+5vni-aj7t.csv https://moto.data.socrata.com/api/views/5vni-aj7t/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Braintree-Police-Department+787k-vdzh.csv https://moto.data.socrata.com/api/views/787k-vdzh/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Upper-Moreland-Township-Police-Department+ipau-aufi.csv https://moto.data.socrata.com/api/views/ipau-aufi/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Kennesaw-Police-Department+7grj-94de.csv https://moto.data.socrata.com/api/views/7grj-94de/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Fort-Peck-Law-and-Justice+95k6-dssn.csv https://moto.data.socrata.com/api/views/95k6-dssn/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Baldwin-Park-Police-Department+295m-pcfh.csv https://moto.data.socrata.com/api/views/295m-pcfh/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Villa-Rica-PD+dgit-z6te.csv https://moto.data.socrata.com/api/views/dgit-z6te/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Macon-County-Sheriff-s-Office+ufni-42kq.csv https://moto.data.socrata.com/api/views/ufni-42kq/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/St-Landry-Parish-Sheriff-s-Office+h64c-3d9x.csv https://moto.data.socrata.com/api/views/h64c-3d9x/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Fort-Peck-Tribal-Health+7qcq-4zzr.csv https://moto.data.socrata.com/api/views/7qcq-4zzr/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Montana-Highway-Patrol-Roosevelt+tdyu-symd.csv https://moto.data.socrata.com/api/views/tdyu-symd/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Canby-Police-Department+pd2i-ie8q.csv https://moto.data.socrata.com/api/views/pd2i-ie8q/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Transylvania-County-Sheriff-s-Office+us3a-4kfa.csv https://moto.data.socrata.com/api/views/us3a-4kfa/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Grantsville-Police-Department+h4i4-5rqg.csv https://moto.data.socrata.com/api/views/h4i4-5rqg/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Fort-Peck-Fish-and-Game+46he-rqhi.csv https://moto.data.socrata.com/api/views/46he-rqhi/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Alvin-Police-Department+id9s-izhe.csv https://moto.data.socrata.com/api/views/id9s-izhe/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Denver-Police-Department+686w-bug2.csv https://moto.data.socrata.com/api/views/686w-bug2/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Seattle-Police-Department+73bx-npzq.csv https://moto.data.socrata.com/api/views/73bx-npzq/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Los-Angeles-Police-Department+dbrj-jyyp.csv https://moto.data.socrata.com/api/views/dbrj-jyyp/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Cheltenham-Township-Police-Department+63mr-f4au.csv https://moto.data.socrata.com/api/views/63mr-f4au/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Cache-County-Sheriff-s-Office+k83u-2hyi.csv https://moto.data.socrata.com/api/views/k83u-2hyi/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Gresham-Police-Department+ycje-xqcv.csv https://moto.data.socrata.com/api/views/ycje-xqcv/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Southern-Utah-University-Public-Safety+jkry-tazz.csv https://moto.data.socrata.com/api/views/jkry-tazz/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Payson-City-Police-Department+aif4-f4nn.csv https://moto.data.socrata.com/api/views/aif4-f4nn/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Clinton-Police-Department+abyf-kpts.csv https://moto.data.socrata.com/api/views/abyf-kpts/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Hurricane-Police-Department+qza6-vde5.csv https://moto.data.socrata.com/api/views/qza6-vde5/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Tremonton-Police-Department+adjt-guzv.csv https://moto.data.socrata.com/api/views/adjt-guzv/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Ephraim-Police-Department+yw5e-u6cp.csv https://moto.data.socrata.com/api/views/yw5e-u6cp/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Santaquin-Police-Department+c7zn-9i7p.csv https://moto.data.socrata.com/api/views/c7zn-9i7p/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Kirkwood-Police-Department+r8dn-mpxt.csv https://moto.data.socrata.com/api/views/r8dn-mpxt/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Park-City-Police-Department+v3uk-a9zw.csv https://moto.data.socrata.com/api/views/v3uk-a9zw/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Sandy-Police-Department+ybbh-65pk.csv https://moto.data.socrata.com/api/views/ybbh-65pk/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Cedar-City-Police-Department+7c8x-7qr2.csv https://moto.data.socrata.com/api/views/7c8x-7qr2/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/North-Park-Police-Department+jf7d-y7iq.csv https://moto.data.socrata.com/api/views/jf7d-y7iq/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Kaysville-Police-Department+djw5-5xe7.csv https://moto.data.socrata.com/api/views/djw5-5xe7/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Rio-Rancho-Police-Department+mkgr-xxwn.csv https://moto.data.socrata.com/api/views/mkgr-xxwn/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Wrightstown-Police-Department+srzq-y3wc.csv https://moto.data.socrata.com/api/views/srzq-y3wc/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Gervais-Police-Department+54jh-dv2a.csv https://moto.data.socrata.com/api/views/54jh-dv2a/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Shelby-County-Sheriff-s-Office+efnu-c2mg.csv https://moto.data.socrata.com/api/views/efnu-c2mg/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/La-Crosse-Police-Department+mi2h-cy8k.csv https://moto.data.socrata.com/api/views/mi2h-cy8k/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Calvert-County-Sheriff-s-Office+5fsp-4scu.csv https://moto.data.socrata.com/api/views/5fsp-4scu/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Enid-Police-Department+cp8s-7bbi.csv https://moto.data.socrata.com/api/views/cp8s-7bbi/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Brian-Head-Marshals-Office+mu66-benf.csv https://moto.data.socrata.com/api/views/mu66-benf/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Onalaska-Police-Department+fq5n-h8s5.csv https://moto.data.socrata.com/api/views/fq5n-h8s5/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Independence-OR-Police-Department+xhtq-728a.csv https://moto.data.socrata.com/api/views/xhtq-728a/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Bonner-Springs-Police-Department+wxdw-jkei.csv https://moto.data.socrata.com/api/views/wxdw-jkei/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Ralston-Police-Department+wukd-9hvt.csv https://moto.data.socrata.com/api/views/wukd-9hvt/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Rutland-City-Police+e7g5-7hf9.csv https://moto.data.socrata.com/api/views/e7g5-7hf9/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Lufkin-Police-Department+94v6-pri7.csv https://moto.data.socrata.com/api/views/94v6-pri7/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/University-of-New-Hampshire+8jk7-nghk.csv https://moto.data.socrata.com/api/views/8jk7-nghk/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Mount-Holly-Police+bni2-rjx5.csv https://moto.data.socrata.com/api/views/bni2-rjx5/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Florida-Atlantic-University-Police+3zz4-6n52.csv https://moto.data.socrata.com/api/views/3zz4-6n52/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Granger-Police-Department+n7zp-mv8y.csv https://moto.data.socrata.com/api/views/n7zp-mv8y/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Arizona-State-University-Police-Department+6fzp-yqnh.csv https://moto.data.socrata.com/api/views/6fzp-yqnh/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Laconia-Police-Department+ebjr-dvdv.csv https://moto.data.socrata.com/api/views/ebjr-dvdv/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Beckley-Police-Department+enmj-5ta6.csv https://moto.data.socrata.com/api/views/enmj-5ta6/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/University-of-Maryland-Police+azcw-w48y.csv https://moto.data.socrata.com/api/views/azcw-w48y/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Midlothian-Police-Department+xg25-jcmp.csv https://moto.data.socrata.com/api/views/xg25-jcmp/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Moxee-Police-Department+dktm-zzbp.csv https://moto.data.socrata.com/api/views/dktm-zzbp/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Hoquiam-Police-Department+8vn7-xz4y.csv https://moto.data.socrata.com/api/views/8vn7-xz4y/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Turner-Police-Department+i95b-sghd.csv https://moto.data.socrata.com/api/views/i95b-sghd/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Germantown-Police-Department+7kwa-dbxd.csv https://moto.data.socrata.com/api/views/7kwa-dbxd/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Winchester-Police-Department+hpsu-r8bz.csv https://moto.data.socrata.com/api/views/hpsu-r8bz/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Kinston-DPS+fugh-j2w2.csv https://moto.data.socrata.com/api/views/fugh-j2w2/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Logan-City-Police-Department+rih3-uhsb.csv https://moto.data.socrata.com/api/views/rih3-uhsb/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Watauga-Police-Department+turg-k5ub.csv https://moto.data.socrata.com/api/views/turg-k5ub/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Zillah-Police-Department+9e6m-w2xg.csv https://moto.data.socrata.com/api/views/9e6m-w2xg/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Marple-Township-Police-Department+5wjs-3uzn.csv https://moto.data.socrata.com/api/views/5wjs-3uzn/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Martin-Police-Department+jhne-k9ft.csv https://moto.data.socrata.com/api/views/jhne-k9ft/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Mabton-Police-Department+5xpf-6nkv.csv https://moto.data.socrata.com/api/views/5xpf-6nkv/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Kearney-Police-Department+u6ka-y5zn.csv https://moto.data.socrata.com/api/views/u6ka-y5zn/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Sherman+eew7-9wyz.csv https://moto.data.socrata.com/api/views/eew7-9wyz/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Red-Bank-Police-Department+sm7x-s23x.csv https://moto.data.socrata.com/api/views/sm7x-s23x/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Enoch-City-Police-Department+77yx-7g9f.csv https://moto.data.socrata.com/api/views/77yx-7g9f/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Central-Saanich-Police-Service+c43q-iph2.csv https://moto.data.socrata.com/api/views/c43q-iph2/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Kent-Police-Department+w4j8-47pg.csv https://moto.data.socrata.com/api/views/w4j8-47pg/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/University-of-South-Alabama+an2u-jsj2.csv https://moto.data.socrata.com/api/views/an2u-jsj2/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Shelton-Police-Department+pmvg-y7ax.csv https://moto.data.socrata.com/api/views/pmvg-y7ax/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Grand-County-Sheriff-s-Office+eq3i-8fq4.csv https://moto.data.socrata.com/api/views/eq3i-8fq4/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/University-of-Illinois-Police-Department+3h5f-6xbh.csv https://moto.data.socrata.com/api/views/3h5f-6xbh/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Blythe-Police-Department+xsep-zcps.csv https://moto.data.socrata.com/api/views/xsep-zcps/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Crisfield-Police-Department+puvr-jfpe.csv https://moto.data.socrata.com/api/views/puvr-jfpe/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Easton-Police-Department+ts48-fmnx.csv https://moto.data.socrata.com/api/views/ts48-fmnx/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Watertown-Police-Department+nqm4-baah.csv https://moto.data.socrata.com/api/views/nqm4-baah/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Ashland-Police-Department+cjsd-rm7h.csv https://moto.data.socrata.com/api/views/cjsd-rm7h/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Rutland-County+t7im-pgnf.csv https://moto.data.socrata.com/api/views/t7im-pgnf/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Cortez-Police-Department+ie22-s6ks.csv https://moto.data.socrata.com/api/views/ie22-s6ks/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Huron-Police-Department+kqt4-77ui.csv https://moto.data.socrata.com/api/views/kqt4-77ui/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Delmar-Police-Department+xs4s-jh3m.csv https://moto.data.socrata.com/api/views/xs4s-jh3m/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/South-Ogden-Police-Department+dzhx-cr5s.csv https://moto.data.socrata.com/api/views/dzhx-cr5s/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Roy-City-Police-Department+e3uz-s2ij.csv https://moto.data.socrata.com/api/views/e3uz-s2ij/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Sullivan-County+hbqn-p2ne.csv https://moto.data.socrata.com/api/views/hbqn-p2ne/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Smithfield-City-Police-Department+nqpf-qand.csv https://moto.data.socrata.com/api/views/nqpf-qand/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Pooler-Police-Department+izt6-p7ax.csv https://moto.data.socrata.com/api/views/izt6-p7ax/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Swanzey-Police-Department+xued-e5yf.csv https://moto.data.socrata.com/api/views/xued-e5yf/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Pleasant-View-Police-Department+6fc2-bskr.csv https://moto.data.socrata.com/api/views/6fc2-bskr/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Dillard-University+w8cx-gxdt.csv https://moto.data.socrata.com/api/views/w8cx-gxdt/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Hubbard-Police-Department+7dnp-rhv5.csv https://moto.data.socrata.com/api/views/7dnp-rhv5/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Toledo-Police-Department+y6du-4qnw.csv https://moto.data.socrata.com/api/views/y6du-4qnw/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Carrollton-Police-Department+ian5-djnh.csv https://moto.data.socrata.com/api/views/ian5-djnh/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Brookline-Police-Department+74p7-am4a.csv https://moto.data.socrata.com/api/views/74p7-am4a/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Roosevelt-County-Sheriff-s-Office+9ara-fbpu.csv https://moto.data.socrata.com/api/views/9ara-fbpu/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/UMBC-Police-Department+9k7a-yxxk.csv https://moto.data.socrata.com/api/views/9k7a-yxxk/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Exeter-Police-Department+4tj6-ucvv.csv https://moto.data.socrata.com/api/views/4tj6-ucvv/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Frostburg-Police-Department+334w-88r3.csv https://moto.data.socrata.com/api/views/334w-88r3/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Salina-City-Police-Department+84rd-rnh9.csv https://moto.data.socrata.com/api/views/84rd-rnh9/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Strasburg-Police-Department+wi9n-8w5s.csv https://moto.data.socrata.com/api/views/wi9n-8w5s/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Haltom-City-Police-Department+irih-38ui.csv https://moto.data.socrata.com/api/views/irih-38ui/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Millard-County-Sheriff-s-Office+xkdd-8yie.csv https://moto.data.socrata.com/api/views/xkdd-8yie/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Easley-Police-Department+mkdt-jhc8.csv https://moto.data.socrata.com/api/views/mkdt-jhc8/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Essex-Police-Department+dr48-r3fr.csv https://moto.data.socrata.com/api/views/dr48-r3fr/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Clallam-Law-Enforcement+cjyf-nuih.csv https://moto.data.socrata.com/api/views/cjyf-nuih/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Carthage-Police+icrn-3tw9.csv https://moto.data.socrata.com/api/views/icrn-3tw9/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/North-Platte+ubef-a7r6.csv https://moto.data.socrata.com/api/views/ubef-a7r6/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Iron-County-Sheriff-s-Office+mie5-i2ze.csv https://moto.data.socrata.com/api/views/mie5-i2ze/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Waxhaw-Police-Department+ec46-6auq.csv https://moto.data.socrata.com/api/views/ec46-6auq/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Laurinburg-Police+q6mf-nf52.csv https://moto.data.socrata.com/api/views/q6mf-nf52/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Clarksville-Police-Department+3fxc-ji94.csv https://moto.data.socrata.com/api/views/3fxc-ji94/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Mount-Pleasant-Police-Department+cta9-zknv.csv https://moto.data.socrata.com/api/views/cta9-zknv/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Chambersburg-Police-Department+ed55-adaq.csv https://moto.data.socrata.com/api/views/ed55-adaq/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Kootenai-County-Sheriffs-Department+u6sm-bi4d.csv https://moto.data.socrata.com/api/views/u6sm-bi4d/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Moore-Police-Department+7yas-memp.csv https://moto.data.socrata.com/api/views/7yas-memp/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Gun-Barrel-City-Police-Department+jj48-cbk6.csv https://moto.data.socrata.com/api/views/jj48-cbk6/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Deephaven-Police-Department+gnfc-rgjd.csv https://moto.data.socrata.com/api/views/gnfc-rgjd/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/West-Warwick-Police-Department+pr6s-m9q7.csv https://moto.data.socrata.com/api/views/pr6s-m9q7/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/University-of-Virginia+kpvm-4qbh.csv https://moto.data.socrata.com/api/views/kpvm-4qbh/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Rogers-Police-Department+2nbb-3zds.csv https://moto.data.socrata.com/api/views/2nbb-3zds/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Mount-Pleasant-Police-Department+iz8s-up4z.csv https://moto.data.socrata.com/api/views/iz8s-up4z/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Sioux-Falls-Police-Department+f2xd-92hn.csv https://moto.data.socrata.com/api/views/f2xd-92hn/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Metter-Police-Department+6cgy-42qj.csv https://moto.data.socrata.com/api/views/6cgy-42qj/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Rantoul-Police-Department+yw6k-vbuf.csv https://moto.data.socrata.com/api/views/yw6k-vbuf/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Lethbridge-Regional-Police-Service+puzi-duhu.csv https://moto.data.socrata.com/api/views/puzi-duhu/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Sheridan-Police-Department+m46t-33ck.csv https://moto.data.socrata.com/api/views/m46t-33ck/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Atlanta-Police-Department+rirb-xfw6.csv https://moto.data.socrata.com/api/views/rirb-xfw6/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Willis-Police-Department+7ypk-4bwe.csv https://moto.data.socrata.com/api/views/7ypk-4bwe/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Hazelwood-Police-Department+a597-dyy4.csv https://moto.data.socrata.com/api/views/a597-dyy4/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Commerce-City-Police-Department+a3tn-hhag.csv https://moto.data.socrata.com/api/views/a3tn-hhag/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Michigan-State-University+di7q-3jg7.csv https://moto.data.socrata.com/api/views/di7q-3jg7/rows.csv?accessType=DOWNLOAD  --wait=30
wget -O /home/nhoss003/socrata2/Louisiana-State-University+msgs-9u3n.csv https://moto.data.socrata.com/api/views/msgs-9u3n/rows.csv?accessType=DOWNLOAD  --wait=30
